export default [
  {
    topicName: "Array",
    position: 0,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Url: "https://www.codingninjas.com/codestudio/problems/two-sum_839653",
        Topic: "Array",
        Difficulty: "Easy",
        Problem: "Two Sum",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
        Topic: "Array",
        Difficulty: "Easy",
        Problem: "Best Time to Buy and Sell Stock",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/ninja-and-sorted-arrays_1214628",
        Topic: "Array",
        Difficulty: "Easy",
        Problem: "ninja-and-sorted-arrays",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/pascal-s-triangle_1089580",
        Topic: "Array",
        Difficulty: "Easy",
        Problem: "pascal-s-triangle",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/stocks-are-profitable_893405",
        Topic: "Array",
        Difficulty: "Easy",
        Problem: "stocks-are-profitable",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/occurs-once_1214969",
        Topic: "Array",
        Difficulty: "Easy",
        Problem: "occurs-once",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://leetcode.com/problems/contains-duplicate/",
        Topic: "Array",
        Difficulty: "Easy",
        Problem: "contains-duplicate",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/majority-element_842495",
        Topic: "Array",
        Difficulty: "Easy",
        Problem: "majority-element",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/duplicate-in-array_893397",
        Topic: "Array",
        Difficulty: "Easy",
        Problem: "duplicate-in-array",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/move-zeros-to-left_1094877",
        Topic: "Array",
        Difficulty: "Easy",
        Problem: "move-zeros-to-left",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
    ],
  },
  {
    topicName: "Recursion",
    position: 1,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Url: "https://www.codingninjas.com/codestudio/problem-details/power-of-two_893061",
        Topic: "Recursion",
        Difficulty: "Easy",
        Problem: "power-of-two",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/find-power-of-a-number_893198",
        Topic: "Recursion",
        Difficulty: "Easy",
        Problem: "find-power-of-a-numbe",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/reverse-the-singly-linked-list_799897",
        Topic: "Recursion",
        Difficulty: "Easy",
        Problem: "reverse-the-singly-linked-list",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/ninja-and-sorted-arrays_1214628",
        Topic: "Recursion",
        Difficulty: "Easy",
        Problem: "ninja-and-sorted-arrays",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problem-details/reverse-the-string_799927",
        Topic: "Recursion",
        Difficulty: "Easy",
        Problem: "reverse-the-string",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
    ],
  },
  {
    topicName: "Binary Search",
    position: 2,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Url: "https://www.codingninjas.com/codestudio/problem-details/binary-search_972",
        Topic: "Binary_Search",
        Difficulty: "Easy",
        Problem: "binary-search",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/valid-perfect-square_1082552",
        Topic: "Binary_Search",
        Difficulty: "Easy",
        Problem: "valid-perfect-square",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://leetcode.com/problems/guess-number-higher-or-lower/",
        Topic: "Binary_Search",
        Difficulty: "Easy",
        Problem: "guess-number-higher-or-lower",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problem-details/find-peak-element_1081482",
        Topic: "Binary_Search",
        Difficulty: "Easy",
        Problem: "find-peak-element",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/square-root-integral_893351",
        Topic: "Binary_Search",
        Difficulty: "Medium",
        Problem: "square-root-integral",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
    ],
  },
  {
    topicName: "Stack",
    position: 3,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Url: "https://leetcode.com/problems/min-stack/",
        Topic: "Stack",
        Difficulty: "Easy",
        Problem: "min-stack",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://leetcode.com/problems/next-greater-element-i/",
        Topic: "Stack",
        Difficulty: "Easy",
        Problem: "next-greater-element-1",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://leetcode.com/problems/implement-stack-using-queues/",
        Topic: "Stack",
        Difficulty: "Easy",
        Problem: "implement-queue-using-stacks",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problem-details/stack-using-queue_795152",
        Topic: "Stack",
        Difficulty: "Easy",
        Problem: "Stack using queue",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/maximum-nesting-depth-of-two-valid-parentheses-strings_1461222",
        Topic: "Stack",
        Difficulty: "Easy",
        Problem: "maximum nesting depth of two valid parentheses strings",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
    ],
  },
  {
    topicName: "LinkedList",
    position: 4,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Url: "https://www.codingninjas.com/codestudio/problems/delete-node-in-ll_5881",
        Topic: "Linkedlist",
        Difficulty: "Easy",
        Problem: "delete node in linked list",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/middle-of-linked-list_973250",
        Topic: "Linkedlist",
        Difficulty: "Easy",
        Problem: "middle-of-the-linked-list",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/binary-to-integer_2421938",
        Topic: "Linkedlist",
        Difficulty: "Easy",
        Problem: "binary to integer",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/remove-duplicates-from-unsorted-linked-list_1069331",
        Topic: "Linkedlist",
        Difficulty: "Easy",
        Problem: "remove duplicates from unsorted linked list",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/merge-two-sorted-linked-lists_800332",
        Topic: "Linkedlist",
        Difficulty: "Easy",
        Problem: "merge two sorted linked list",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problem-details/cycle-detection-in-a-singly-linked-list_628974",
        Topic: "Linkedlist",
        Difficulty: "Easy",
        Problem: "cycle detection in a singly linked list",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/intersection-of-linked-list_630457",
        Topic: "Linkedlist",
        Difficulty: "Easy",
        Problem: "intersectiion of linked list",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/palindrom-linked-list_799352?leftPanelTab=0",
        Topic: "Linkedlist",
        Difficulty: "Medium",
        Problem: "palindrome linke list",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/remove-all-nodes-with-value-k_1262145",
        Topic: "Linkedlist",
        Difficulty: "Medium",
        Problem: "remove all nodes with value k",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/browser_2427908",
        Topic: "Linkedlist",
        Difficulty: "Medium",
        Problem: "reverse-linked-list",
        Done: "FALSE",
        Bookmark: "FALSE",
        Notes: "",
        Solution: "",
      },
    ],
  },
  {
    topicName: "Matrix",
    position: 5,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Url: "https://leetcode.com/problems/richest-customer-wealth/",
        Topic: "Matrix",
        Difficulty: "Easy",
        Problem: "richest-customer-wealth",
        Done: "",
        Bookmark: "",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://leetcode.com/problems/matrix-diagonal-sum/",
        Topic: "Matrix",
        Difficulty: "Easy",
        Problem: "matrix-diagonal-sum",
        Done: "",
        Bookmark: "",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://leetcode.com/problems/flipping-an-image/",
        Topic: "Matrix",
        Difficulty: "Easy",
        Problem: "flipping-an-image",
        Done: "",
        Bookmark: "",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/total-negative-numbers-in-a-sorted-matrix_3161878",
        Topic: "Matrix",
        Difficulty: "Easy",
        Problem: "total-negative-numbers-in-a-sorted-matrix",
        Done: "",
        Bookmark: "",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://leetcode.com/problems/lucky-numbers-in-a-matrix/",
        Topic: "Matrix",
        Difficulty: "Easy",
        Problem: "lucky-numbers-in-a-matrix",
        Done: "",
        Bookmark: "",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://leetcode.com/problems/reshape-the-matrix/",
        Topic: "Matrix",
        Difficulty: "Medium",
        Problem: "reshape-the-matrix",
        Done: "",
        Bookmark: "",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problems/buildings-projection_1466964",
        Topic: "Matrix",
        Difficulty: "Medium",
        Problem: "buildings-projection",
        Done: "",
        Bookmark: "",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://leetcode.com/problems/available-captures-for-rook/",
        Topic: "Matrix",
        Difficulty: "Medium",
        Problem: "available captures for toot",
        Done: "",
        Bookmark: "",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://leetcode.com/problems/toeplitz-matrix/",
        Topic: "Matrix",
        Difficulty: "Medium",
        Problem: "toeplitz matrix",
        Done: "",
        Bookmark: "",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://leetcode.com/problems/special-positions-in-a-binary-matrix/",
        Topic: "Matrix",
        Difficulty: "Medium",
        Problem: "special postions in a binary matrix",
        Done: "",
        Bookmark: "",
        Notes: "",
        Solution: "",
      },
    ],
  },
  {
    topicName: "String",
    position: 6,
    started: false,
    doneQuestions: 0,
    questions: [
      {
        Url: "https://leetcode.com/problems/jewels-and-stones/",
        Topic: "String",
        Difficulty: "Easy",
        Problem: "jewels and stones",
        Done: "",
        Bookmark: "",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://leetcode.com/problems/sorting-the-sentence/",
        Topic: "String",
        Difficulty: "Easy",
        Problem: "sorting the sentence",
        Done: "",
        Bookmark: "",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://leetcode.com/problems/to-lower-case/",
        Topic: "String",
        Difficulty: "Easy",
        Problem: "to lower case",
        Done: "",
        Bookmark: "",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://leetcode.com/problems/determine-if-string-halves-are-alike/",
        Topic: "String",
        Difficulty: "Easy",
        Problem: "determine if string halves are alike",
        Done: "",
        Bookmark: "",
        Notes: "",
        Solution: "",
      },
      {
        Url: "https://www.codingninjas.com/codestudio/problem-details/reverse-the-string_799927",
        Topic: "String",
        Difficulty: "Easy",
        Problem: "reverse the string",
        Done: "",
        Bookmark: "",
        Notes: "",
        Solution: "",
      },
    ],
  },
];
export const version = 100000022;
